# Agent-based Transportaion Model (Washington DC)

In [12]:
from pyrosm import OSM, get_data

region = "district-of-columbia"
fp = get_data(region)
osm = OSM(fp)
osm.keep_node_info = True
network = osm.get_network(
    "all",
    extra_attributes=[
        "lanes:forward",
        "lanes:backward",
        "cycleway:left",
        "cycleway:right",
    ],
    nodes=True,
)

In [13]:
network[0].head(1)

,changeset,timestamp,lon,version,lat,visible,tags,id,geometry
0,0,1421734870,-77.108261,3,38.935738,False,"{'highway': 'traffic_signals', 'source': 'surv...",1391829849,POINT (-77.10826 38.93574)

In [14]:
network[1].head(1)

,access,area,bicycle,bridge,cycleway,est_width,foot,footway,highway,junction,...,id,nodes,timestamp,version,tags,osm_type,geometry,u,v,length
0,None,None,None,None,None,None,None,None,residential,None,...,4681186,"[1391829849, 281072, 3299878446, 3299878455, 2...",1613445127,5,"{""visible"":false}",way,"LINESTRING (-77.10826 38.93574, -77.10825 38.9...",1391829849,281072,11.048

In [15]:
graph = osm.to_graph(network[0], network[1], "networkx")

In [16]:
graph.nodes[1391829849]

{'changeset': 0,
 'timestamp': 1421734870,
 'x': -77.10826110839844,
 'version': 3,
 'y': 38.93573760986328,
 'visible': False,
 'tags': {'highway': 'traffic_signals', 'source': 'survey'},
 'osmid': 1391829849,
 'geometry': <POINT (-77.108 38.936)>}

In [17]:
graph.edges[(1391829849, 281072, 0)]

{'access': None,
 'area': None,
 'bicycle': None,
 'bridge': None,
 'cycleway': None,
 'est_width': None,
 'foot': None,
 'footway': None,
 'highway': 'residential',
 'junction': None,
 'lanes': None,
 'lit': None,
 'maxspeed': None,
 'motorcar': None,
 'motor_vehicle': None,
 'name': None,
 'oneway': None,
 'overtaking': None,
 'psv': None,
 'ref': None,
 'service': None,
 'segregated': None,
 'sidewalk': None,
 'smoothness': None,
 'surface': None,
 'tracktype': None,
 'tunnel': None,
 'turn': None,
 'width': None,
 'lanes:forward': None,
 'lanes:backward': None,
 'cycleway:left': None,
 'cycleway:right': None,
 'osmid': 4681186,
 'nodes': [1391829849, 281072, 3299878446, 3299878455, 2921446557],
 'timestamp': 1613445127,
 'version': 5,
 'tags': '{"visible":false}',
 'osm_type': 'way',
 'geometry': <LINESTRING (-77.108 38.936, -77.108 38.936)>,
 'u': 1391829849,
 'v': 281072,
 'length': 11.048,
 'key': 0}